# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gotail < Formula
  desc "Bootstrap Tailscale into your Raspberry Pi from the very first boot."
  homepage "https://github.com/borisdvlpr/gotail"
  version "1.0.0"
  license "BSD-3-Clause"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/borisdvlpr/gotail/releases/download/v1.0.0/gotail_Darwin_x86_64.tar.gz"
      sha256 "6a9737b3d688aaef0ce95c1bb0f9aaa66a906726f3f24e6ac2aa304db0cde420"

      define_method(:install) do
        bin.install "gotail"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/borisdvlpr/gotail/releases/download/v1.0.0/gotail_Darwin_arm64.tar.gz"
      sha256 "d1f809493a504f2f41d58122595c43b5e1e04cbf5038d274f2fede3ef741bdd8"

      define_method(:install) do
        bin.install "gotail"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/borisdvlpr/gotail/releases/download/v1.0.0/gotail_Linux_x86_64.tar.gz"
      sha256 "a967aaf870fc1a904f0b16b291de06fbf487ee9cf3b310dce21721e97b56833a"
      define_method(:install) do
        bin.install "gotail"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/borisdvlpr/gotail/releases/download/v1.0.0/gotail_Linux_armv6.tar.gz"
      sha256 "d52e5089d8a4274e585a7d470f7677567cc669d138317661dbf83ade96a7d58d"
      define_method(:install) do
        bin.install "gotail"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/borisdvlpr/gotail/releases/download/v1.0.0/gotail_Linux_arm64.tar.gz"
      sha256 "b685598a430a8cc40b4a7b8bf135468a8af3341e8e25da50cfe32bf59583e7b5"
      define_method(:install) do
        bin.install "gotail"
      end
    end
  end

  test do
    system "#{bin}/gotail --version"
  end
end
