# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gotail < Formula
  desc "Bootstrap Tailscale into your Raspberry Pi from the very first boot."
  homepage "https://github.com/borisdvlpr/gotail"
  version "1.0.0"
  license "BSD-3-Clause"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/borisdvlpr/gotail/releases/download/v1.0.0/gotail_Darwin_x86_64.tar.gz"
      sha256 "ca70aa5054d8241b4b625bffb3f9b5016c0a4e7c96775da36d1a9930e04a7395"

      define_method(:install) do
        bin.install "gotail"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/borisdvlpr/gotail/releases/download/v1.0.0/gotail_Darwin_arm64.tar.gz"
      sha256 "90defe53da42e3334d288dcdd342aa96331fc5d18b05962d8fb248bd8b1529e0"

      define_method(:install) do
        bin.install "gotail"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/borisdvlpr/gotail/releases/download/v1.0.0/gotail_Linux_x86_64.tar.gz"
      sha256 "f58d844d8a6f55439fda86f61904ba1f5bc1784bc924c7bc0bddf1b6a289d34d"
      define_method(:install) do
        bin.install "gotail"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/borisdvlpr/gotail/releases/download/v1.0.0/gotail_Linux_armv6.tar.gz"
      sha256 "cfac6f9679c3c1293950ee95ab2882c80ba6f103a17b802bda16c099f5c863fe"
      define_method(:install) do
        bin.install "gotail"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/borisdvlpr/gotail/releases/download/v1.0.0/gotail_Linux_arm64.tar.gz"
      sha256 "6f4a0e4d6d82bb2e9079e918c66c2c280685ed4c9f23810fd55244daf0d0c705"
      define_method(:install) do
        bin.install "gotail"
      end
    end
  end

  test do
    system "#{bin}/gotail --version"
  end
end
